language: node_js
node_js:
- stable
install: npm install
cache:
  npm: false
jobs:
  include:
  - name: Deploy to staging
    if: branch = master
    stage: Deployment
    script: npm run build
    deploy:
      on: master
      provider: heroku
      skip_cleanup: true
      api_key:
        secure: PcAXKO75G2p5zI01pchNcareN5cM0NKN/z3tf5Awh201+V8zIwqso1BFz/qUGMj1vTw7dnt22i7o345dXwPFFiGn4ShQgto/56qwlTN86bgTbiCGOVxlfYSr/m8IjUHDpxNBjOM7z1ZZwWPSaBvfp8XcjZrHvs1mL/ZpWO36TyFF6oR9FHq189FCfDDbKg3RZvoGnHxgY2ITnRGR29wwkusk6+tmjS1MnX01pfBDXo0hrF/j7/T6SV0Uwu3g2mAX69lGSDgW2h8Cgpg7/89qDPfVLSsTUaU0BTP5nFw/+gZP1efg6tmdPA2c8wiyYGbfwgSctrFQYDcY0f4AM9CiJxr0VbK3xnuhiTajQQME8l6j+gVN3TZ9TX45XnrajdhQkc5JnKChoQ19j4ghYVuQW5c9/JaPtr3bglwplaurcPxGv0ERHtBWJMe9vRmDZvbcXWLJE174eSXwzC2sv/WYBRV5qM7reGNoy0oBf9JUhUWjWmSYw07CR/hvfA8D3C/qia2Q2Y5eM2i6pGxspqAwJfqg0RoMaB5LTyoBtdIgTyXplNIJAsWRkY6lGnQKVUNmb+npKMR+1fF7wbNxhu2AF1obnYAtLExqosq+ZbY/9U9VAUaYiOxoGJ2YHbfLKgYxG5a9nI8xGA2wxPtRviYk2Knbf7MDQbglNURW0iPQLZk=
      app: hackalgo
stages:
- Deployment