language: node_js
node_js:
- stable
install: npm install
cache:
  npm: false
jobs:
  include:
  - name: Deploy to staging
    if: branch = master
    stage: Deployment
    script: npm run build
    deploy:
      on: master
      provider: heroku
      skip_cleanup: true
      api_key:
        secure: pde1Zr63OOzPwRHbZ23V+q1+LYWxs7+sMvUKmAHYuYtvxD/QfNjuqXbDJrJqJzwEkQnXEYlG2sOl0g9X+U8YVHtnQ5Pz6qWKe0Yk5SVo4/UCjakj41Wzx9eeH9wDk94jAmiDPMmAvGsvXtV+6PU8lfv34oFYyXHUJMUm33QY8NQjYs1STbWQU+tSgWpvUOI6ikU4mOagI00EqcP4y8sDlzJFnSaBlkMZYyWgAusQ5eliB7of/kVOFWn9NqnlIEnR9xa2Ja8VpIz1rGxiiIG/u4NektcixcmXyz8xURFzcmcjcR4y6AYPwEafQdmggYA4ohX7bIoZiqUEfa55+U/juVUeZiPCT5TA7deH0Dz01KJ90gmyJYGdY/E5W5jzaxXsAkjqsC5qvV7GVa+bqM4yBn5U7TMeh8xobE1nbfenU2/QvA40kzXg95/+DFgQAf6UGsXbDmmynrGjaJYhfIYjpIESIDZFT6E375wTeWNWBLrqFOugvREX4rmko1b6pDFkEzvlRKFZJk8rd+u7yQB0PgDhTQzxrQG3oamJh279WgksP2tiMEqXgPtSxHm46+oJE5tIp5YTMldwrt0j5TChxI3xFuXuAkAgWhM4XtbdRInnPhNDVgprC+jZafE/IdAtSmYvT+eGSfO71lsfP8okmIku+EpuNuLH/Wf99C1FC6A=
      app: hackalgo
stages:
- Deployment