language: node_js
node_js:
- stable
install: npm install
cache:
  npm: false
jobs:
  include:
  - name: Deploy to staging
    if: branch = master
    stage: Deployment
    script: npm run build
    deploy:
      on: master
      provider: heroku
      skip_cleanup: true
      api_key:
        secure: oLGUbTm8fKLpd6xN+oEPOJ/7HsuFsIPjCn5XqeozpEWP0fbt/831FmYRCwAqm20L+nJKZyTgI672oDOpSwG+4Eljn8tl0ThoNkedQwDOMUOLMkSpOZkSv8zLoda2xdwIbQICRXHKXV9CRfwWlg7g6ph1gXYTSmAmvjP4w/8NAVbeLpev7rD+C+agvjjV3E/j4czn00fkhePyAqRl3GyARzOJ7mcDshZTy4l92slmA+9mA5ze0BJK3wXPasYMjGqqoKmFr5r705CynMxvAnKUVaVoGIFg+tUpUU/Q1z//usjLcJMRN71y3RL9HKZCqB3EsTXMvifgK4mQVydAuMIBy6CfiaZ+Xbd2x81Qh5HMWRyuD9uopqheAj3LgXROGJj7fJEXYnMnsvgzRYWUiO1YkLJw/F92gOSH3I9Rog6Txkb5F05JVuAbChoOr03mfNWVhMQxJ6U9bfD4FBGWRT/9fwlnMbKXd7TMM8MHSbfbpLpqLo/iMNiJ7yDwXypl5xNprZMcqgMoOrCYtH00lQyJbm8WW8FbQqHQIPN/nfDKrf0WVBxjyGlYxRM3/4rE+H6v06nPEzC/ewp6iDAUoH8hgAncFpMnYfYWy/9I2huQ08bFCd+PvUDD2gJEq9xWSMqPF+4vTc+t5Az9stYmvtGzR3REqKAVXHOFtlB003B1czA=
      app: hackalgo
stages:
- Deployment